name: imperial_persian_date
description: "A Flutter package for Imperial Persian (Shahanshahi) calendar. Converts between Gregorian, Solar Hijri (Shamsi), and Imperial Persian dates. Current Imperial year = Shamsi year + 1180."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/imperial_persian_date"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


