name: imperial_persian_date
description: "Imperial Persian (Shahanshahi) calendar converter for Gregorian, Shamsi, and Imperial dates."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/imperial_persian_date"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


